---
- name: Install libselinux-python for SELinux
  action: yum name=libselinux-python state=present

- lineinfile: dest=/etc/yum/pluginconf.d/fastestmirror.conf insertafter="EOF" line="include_only=.jp" state=present

- name: Install basic packages
  action: yum name={{ item }} state=present
  with_items:  basic_packages

- service: name=ntpd state=started enabled=yes

- selinux: policy=targeted state=permissive

- name: Check timezone
  command: date +%Z
  register: centos_timezone

- name: Copy timezone file
  copy: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime owner=root group=root mode=0644
  when: centos_timezone.stdout == "UTC"

- name: Set timezone
  lineinfile: dest=/etc/sysconfig/clock regexp=^ZONE= line=ZONE="Asia/Tokyo" state=present
